name: default

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip=21.3.1
  - ipykernel=6.7.0
  - pip:
      - meson>=0.55
      - toml>=0.10
      - protobuf==3.19.4
      - ninja==1.10.0
      - docker==5.0.3
      - jinja2==3.1.2
      - toml==0.10.2
      - pyyaml==6.0