name: "build containers"

on:
  push:
    branches:
      - master

jobs:
  build-containers:
    runs-on: ubuntu-20.04

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: "${{ github.event_name != 'pull_request' }}"
          tags: docker.pkg.github.com/${{ github.repository }}/fedn:latest
          file: Dockerfile